### ISSUE TITLE
Ask about the source of active learning dataset

### ISSUE THREAD

**Issue by ivokun** [af1tang/personaGPT#1]
Hi,

It's an interesting approach and the results are looking good in your method.
But, I couldn't find any source or an explanation about your "active learning dataset". In your code, its only imports the pickled version of the data. 

Could you cite or put a link in the README for the source of active dataset?

Thanks!

**Comment by af1tang** [comment]
Hi ivokun, 

I have updated the active learning data to .csv format instead of pickle. Just submitted the preprint paper which details the data acquisition process to arXiv.

I have released the training code to do active learning: https://github.com/af1tang/convogym. It should be PIP installable (let me know if it isn't). The data section here has methods to process both personachat as well as active learning data for training. 

Best,

af1tang
